"""Mock of the external /v1/blacklist API consumed by the Aurelia pipeline.

Serves the JSON generated by scripts/generate_data.py. Read-only.

The file is read on every request rather than cached at startup so the
DAG's ingest task always sees the latest snapshot when the seed is
regenerated (idempotent re-runs during development).
"""
from __future__ import annotations

import json
import os
from pathlib import Path

from fastapi import FastAPI, HTTPException

BLACKLIST_PATH = Path(os.getenv("BLACKLIST_JSON_PATH", "/data/raw/blacklist.json"))

app = FastAPI(
    title="Aurelia Blacklist Mock",
    description="Mock of the external /v1/blacklist endpoint.",
    version="1.0.0",
)


@app.get("/healthz", tags=["ops"])
def healthz() -> dict:
    return {"status": "ok"}


@app.get("/v1/blacklist", tags=["blacklist"])
def get_blacklist() -> dict:
    if not BLACKLIST_PATH.exists():
        raise HTTPException(
            status_code=503,
            detail=(
                f"Blacklist file not found at {BLACKLIST_PATH}. "
                "Run scripts/generate_data.py (the pipeline's first DAG task) "
                "to seed the raw data."
            ),
        )
    with BLACKLIST_PATH.open() as f:
        return json.load(f)
